services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=example'
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080